version: '3.8'

services:
  nopcommerce_database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: nopcommerce_mssql_server
    environment:
      SA_PASSWORD: "nopCommerce_db_password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - nop_net

  nopcommerce_web:
    build:
      context: .
    container_name: nopcommerce_web
    ports:
      - "8080:80"
    depends_on:
      - nopcommerce_database
    networks:
      - nop_net

volumes:
  mssql_data:

networks:
  nop_net:
